### PR TITLE
Fix bootstrap chicken and egg condition #50

### LINKED ISSUE #50: Bootstrap chicken and egg issue with siteid
To reproduce:

Easier to map config to files just to see whats going on, but the issue is the same with both redis and with files

```
            [
                'conditions' => [
                    'name' => 'core/config',
                ],
                'stores' => ['shared_files'],
            ],
```

Now run this in two tabs:
```
/var/lib/sitedata# grep -r checkcachewebping *
```
and run these commands rerunning above between every command:

```
php admin/cli/purge_caches.php
php admin/cli/cfg.php --component=tool_heartbeat
php admin/cli/cfg.php --component=tool_heartbeat
```

After the first cfg the caches should still be empty. After the second they should be filled. Prior to the patch the first one fills them in the wrong place, and the second results in two pairs of caches

### PR DESCRIPTION
**Pull request by brendanheywood**
Closes #50

### CODE REVIEW

File: classes/cache_factory.php [hunk 1]
```diff
@@ -61,7 +61,11 @@ public function create_config_instance($writer = false) {
             $this->configs[$class]->load();
         }
 
-        $this->set_state(self::STATE_READY);
+        if (empty($CFG->siteidentifier)) {
```
Comment (matthewhilton) [inline classes/cache_factory.php:64]: 1 tiny nit pick - could you put a comment here explaining e.g. why siteidentifier might be null or why its important to disable the cache if it is null

**Review by matthewhilton — COMMENTED** [review]
I tested this on my local instead just watching redis and hitting the front page after purging caches, and it appears to have stopped a whole load of other keys appearing in redis:

| Before | After |
| --- | --- |
|  |  |

Some of these keys though look like lang string storage that is no longer being stored, which is interesting.
Checking the debug info, it looks like this is causing any cache that is not the config cache to use no caching, even on subsequent loads.

| Before | After |
| --- | --- |
|  | image |

Quickly stepping through with xdebug on I can see its hitting https://github.com/catalyst/moodle-tool_forcedcache/pull/51/files#diff-d265ec6c9603db572b0789e13a6e79a2b16bbf7e7ceef4b489ff497c7a9bb7dcR65 a lot while trying to make cache stores, which is strange since it should be set on the second request since the site identifier bootstrap file exists.

**Comment by matthewhilton** [comment]
Turns out I had `$CFG->siteidentifier = ''` in my local which was causing it to never use the cache now with this patch which makes sense, it was doing its job as intended.

**Review by matthewhilton — APPROVED** [review]
